### PR TITLE
Comments on documentation

### PR DESCRIPTION
**Pull request by keflavich**
* [ ] link 'graph' to wiki page on graphs
 * [ ] Word choice question: is "permute" correct here? https://github.com/Astroua/SCIMES/commit/5516b4ae991ba919e7591a20568d0e779d1b36f4
 * [ ] in escalpars, I changed "from" to "associated with" https://github.com/Astroua/SCIMES/commit/5516b4ae991ba919e7591a20568d0e779d1b36f4
 * [ ] Rephrasing that needs review https://github.com/Astroua/SCIMES/commit/41fdc6896de3ed649c7b596b090f7214e999968e
 * [ ] User-set parameters need further exposition in the docs. 41fdc6896de3ed649c7b596b090f7214e999968e
 * [ ] `user_ams` should provide some additional example of what the "appropriate shape" is https://github.com/Astroua/SCIMES/commit/a1603bd0b0342c5b97ab683e52ed55982fd2ed7c

### CODE REVIEW

**Comment by low-sky** [comment]
I think permute is correct for 5516b4a here.  
However, I think the 'prompt' rephrasing in 41fdc68 isn't correct.  I think it just means that the matrices are able to be aggregated without user prompting.  @dcolombo ?

Other than that, thing look good here.

However I think it would be nice if we could provide a small sample data set and a full example script associated with it in the long run.  I'm not sure that the Orion data are freely distributable, so something else maybe?  This probably doesn't need to be done in the near future.

**Comment by keflavich** [comment]
The Orion surveys are here: https://www.cfa.harvard.edu/rtdc/CO/NumberedRegions/DHT27/index.html

**Comment by low-sky** [comment]
That's the one!

**Comment by dcolombo** [comment]
Yes, the original sentence in 41fdc68 means that if more than one matrix is provided or if more than one criterion is selected, the aggregation happens automatically. The user is not called at this stage.

**Pull request merged**
